// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    host, ip_addr, connected_at, last_seen_at
) VALUES (
    $1, $2, NOW(), NOW()
)
RETURNING id, host, ip_addr, connected_at, last_seen_at
`

type CreateClientParams struct {
	Host   string
	IpAddr string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient, arg.Host, arg.IpAddr)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.IpAddr,
		&i.ConnectedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, host, ip_addr, connected_at, last_seen_at FROM clients
WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id int32) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.IpAddr,
		&i.ConnectedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getClients = `-- name: GetClients :many
SELECT id, host, ip_addr, connected_at, last_seen_at FROM clients
`

func (q *Queries) GetClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.IpAddr,
			&i.ConnectedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
