// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id, name, status, priority, created_at
) VALUES (
    gen_random_uuid(), $1, $2, $3, NOW()
)
RETURNING id, name, status, priority, created_at, finished_at, cancelled_at
`

type CreateJobParams struct {
	Name     string
	Status   int32
	Priority int32
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.Name, arg.Status, arg.Priority)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.CancelledAt,
	)
	return i, err
}

const deleteJobs = `-- name: DeleteJobs :exec
DELETE FROM jobs
`

func (q *Queries) DeleteJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteJobs)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, name, status, priority, created_at, finished_at, cancelled_at FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT id, name, status, priority, created_at, finished_at, cancelled_at FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) GetJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWaitingJobs = `-- name: GetWaitingJobs :many
SELECT id, name, status, priority, created_at, finished_at, cancelled_at FROM jobs
WHERE finished_at IS NULL
AND cancelled_at IS NULL
ORDER BY priority DESC, created_at ASC
`

func (q *Queries) GetWaitingJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getWaitingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $2, finished_at = $3, cancelled_at = $4
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID          uuid.UUID
	Status      int32
	FinishedAt  sql.NullTime
	CancelledAt sql.NullTime
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.FinishedAt,
		arg.CancelledAt,
	)
	return err
}
