// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Job struct {
	ID          uuid.UUID
	Name        string
	Status      int32
	Priority    int32
	CreatedAt   time.Time
	FinishedAt  sql.NullTime
	CancelledAt sql.NullTime
}

type Task struct {
	ID          uuid.UUID
	Name        string
	Status      int32
	Command     string
	CreatedAt   time.Time
	FinishedAt  sql.NullTime
	CancelledAt sql.NullTime
	JobID       uuid.UUID
}

type Worker struct {
	ID          uuid.UUID
	Host        string
	Port        string
	ConnectedAt time.Time
	LastSeenAt  time.Time
	Status      int32
}
