// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Worker struct {
	ID          uuid.UUID
	Host        string
	Port        string
	ConnectedAt time.Time
	LastSeenAt  time.Time
	Status      sql.NullString
}
