// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Worker struct {
	ID          int32
	Host        string
	IpAddr      string
	ConnectedAt time.Time
	LastSeenAt  time.Time
}
