// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, name, status, command, created_at, job_id
) VALUES (
    gen_random_uuid(), $1, $2, $3, NOW(), $4
)
RETURNING id, name, status, command, created_at, finished_at, cancelled_at, job_id
`

type CreateTaskParams struct {
	Name    string
	Status  int32
	Command string
	JobID   uuid.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Name,
		arg.Status,
		arg.Command,
		arg.JobID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Command,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.JobID,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, name, status, command, created_at, finished_at, cancelled_at, job_id FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Command,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.CancelledAt,
		&i.JobID,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT id, name, status, command, created_at, finished_at, cancelled_at, job_id FROM tasks
`

func (q *Queries) GetTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Command,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CancelledAt,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByJobId = `-- name: GetTasksByJobId :many
SELECT id, name, status, command, created_at, finished_at, cancelled_at, job_id FROM tasks
WHERE job_id = $1
`

func (q *Queries) GetTasksByJobId(ctx context.Context, jobID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByJobId, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Command,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.CancelledAt,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = $2
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID
	Status int32
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
