// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (
    id, host, port, connected_at, last_seen_at
) VALUES (
    gen_random_uuid(), $1, $2, NOW(), NOW()
)
RETURNING id, host, port, connected_at, last_seen_at, status
`

type CreateWorkerParams struct {
	Host string
	Port string
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker, arg.Host, arg.Port)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.Status,
	)
	return i, err
}

const deleteWorkers = `-- name: DeleteWorkers :exec
DELETE FROM workers
`

func (q *Queries) DeleteWorkers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteWorkers)
	return err
}

const getWorker = `-- name: GetWorker :one
SELECT id, host, port, connected_at, last_seen_at, status FROM workers
WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.Status,
	)
	return i, err
}

const getWorkers = `-- name: GetWorkers :many
SELECT id, host, port, connected_at, last_seen_at, status FROM workers
`

func (q *Queries) GetWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, getWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Port,
			&i.ConnectedAt,
			&i.LastSeenAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE workers
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, id)
	return err
}
