// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package database

import (
	"context"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (
    host, ip_addr, connected_at, last_seen_at
) VALUES (
    $1, $2, NOW(), NOW()
)
RETURNING id, host, ip_addr, connected_at, last_seen_at
`

type CreateWorkerParams struct {
	Host   string
	IpAddr string
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker, arg.Host, arg.IpAddr)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.IpAddr,
		&i.ConnectedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteWorkers = `-- name: DeleteWorkers :exec
TRUNCATE workers
RESTART IDENTITY
`

func (q *Queries) DeleteWorkers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteWorkers)
	return err
}

const getWorker = `-- name: GetWorker :one
SELECT id, host, ip_addr, connected_at, last_seen_at FROM workers
WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id int32) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.IpAddr,
		&i.ConnectedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getWorkers = `-- name: GetWorkers :many
SELECT id, host, ip_addr, connected_at, last_seen_at FROM workers
`

func (q *Queries) GetWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, getWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.IpAddr,
			&i.ConnectedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
