services:
  db:
    image: postgres
    container_name: taskscheduler_postgres
    ports:
      - ${TS_DB_PORT}:5432
    volumes:
      - db:/data/postgres
      - ./sql/docker_db_init:/docker-entrypoint-initdb.d # Init the database schema
    environment:
      POSTGRES_PASSWORD: ${TS_DB_PASSWORD}
      POSTGRES_USER: ${TS_DB_USER}
      POSTGRES_DB: ${TS_DB_NAME}

volumes:
  db:
