### Create worker
POST http://localhost:8080/api/workers
Content-Type: application/json

{
    "host": "testhost",
    "port": "8412"
}

### Clear all workers
DELETE http://localhost:8080/api/workers


### List all workers
GET http://localhost:8080/api/workers


### Delete Jobs
DELETE http://localhost:8080/api/jobs


### Create job
POST http://localhost:8080/api/jobs
Content-Type: application/json

{
    "name": "ping test normal",
    "priority": 200,
    "tasks": [
        {
        "name": "ping 1",
        "command": "ping -c 5 google.com"
        },
        {
        "name": "ping localhost",
        "command": "ping -c 9 127.0.0.1"
        } 
    ]
}

### Create job 
POST http://localhost:8080/api/jobs
Content-Type: application/json

{
    "name": "ping test higher prio",
    "priority": 500,
    "tasks": [
        {
        "name": "ping 1",
        "command": "ping -c 5 google.com"
        },
        {
        "name": "error command",
        "command": "pin g"
        },
        {
        "name": "ping localhost",
        "command": "ping -c 9 127.0.0.1"
        } 
    ]
}
