### Create working job
POST http://localhost:8080/api/jobs
Content-Type: application/json

{
    "name": "ping test normal",
    "priority": 200,
    "tasks": [
        {
        "name": "ping 1",
        "command": "ping -c 5 google.com"
        },
        {
        "name": "ping localhost",
        "command": "ping -c 9 127.0.0.1"
        } 
    ]
}

### Create error job 
POST http://localhost:8080/api/jobs
Content-Type: application/json

{
    "name": "ping test higher prio",
    "priority": 500,
    "tasks": [
        {
        "name": "ping 1",
        "command": "ping -c 5 google.com"
        },
        {
        "name": "error command",
        "command": "pin g"
        },
        {
        "name": "ping localhost",
        "command": "ping -c 9 127.0.0.1"
        } 
    ]
}
