### Create worker
POST http://localhost:8080/api/workers
Content-Type: application/json

{
    "host": "testhost",
    "port": "8412"
}

### Clear all workers
DELETE http://localhost:8080/api/workers


### List all workers
GET http://localhost:8080/api/workers